import type { Incident, Resource, ResponseType } from "@/types/incident";

export const incidentSeed: Incident[] = [
  {
    id: "RX-1042",
    status: "RESPONDING",
    title: "Building fire",
    description:
      "There is a fire in my apartment building. My mother is trapped upstairs and my brother is injured.",
    priority: "CRITICAL",
    createdAt: "2 min ago",
    affectedPeople: 4,
    source: "CITIZEN",
    location: {
      lat: 17.385044,
      lng: 78.486671,
      city: "Hyderabad",
      region: "Telangana",
      label: "Hyderabad, Telangana",
    },
    tags: ["Fire", "Rescue", "Medical"],
    branches: [
      {
        id: "FIRE",
        label: "FIRE RESPONSE",
        situation: "Active building fire",
        recommendedResource: "Fire Team Alpha",
        availability: "AVAILABLE",
        distanceKm: 2.1,
        status: "RESPONDING",
      },
      {
        id: "RESCUE",
        label: "RESCUE REQUIRED",
        situation: "Person trapped upstairs",
        recommendedResource: "Rescue Team 3",
        availability: "AVAILABLE",
        distanceKm: 2.8,
        status: "DISPATCHED",
      },
      {
        id: "MEDICAL",
        label: "MEDICAL RESPONSE",
        situation: "Injured person",
        recommendedResource: "Ambulance 12",
        availability: "AVAILABLE",
        distanceKm: 3.1,
        status: "RESPONDING",
      },
    ],
  },
  {
    id: "RX-1043",
    status: "REVIEWING" as const,
    title: "Flooded street",
    description:
      "A roadside drain overflowed and several vehicles are stranded in the water. People are waiting for help.",
    priority: "HIGH",
    createdAt: "7 min ago",
    affectedPeople: 12,
    source: "CITIZEN",
    location: {
      lat: 17.4566,
      lng: 78.3722,
      city: "Hyderabad",
      region: "Telangana",
      label: "Madhapur, Telangana",
    },
    tags: ["Rescue"],
    branches: [
      {
        id: "RESCUE",
        label: "RESCUE REQUIRED",
        situation: "Vehicles stranded in water",
        recommendedResource: "Rescue Team 2",
        availability: "AVAILABLE",
        distanceKm: 3.4,
        status: "OPEN",
      },
    ],
  },
  {
    id: "RX-1044",
    status: "OPEN",
    title: "Food shortage at temporary shelter",
    description:
      "The shelter is running short on food and water for families displaced by the storm.",
    priority: "MEDIUM",
    createdAt: "15 min ago",
    affectedPeople: 127,
    source: "CITIZEN",
    location: {
      lat: 17.4117,
      lng: 78.4017,
      city: "Hyderabad",
      region: "Telangana",
      label: "Secunderabad, Telangana",
    },
    tags: ["NGO", "Food"],
    branches: [
      {
        id: "FOOD",
        label: "FOOD SUPPORT",
        situation: "Shelter food emergency",
        recommendedResource: "NGO Unit 4",
        availability: "AVAILABLE",
        distanceKm: 3.2,
        status: "OPEN",
      },
      {
        id: "WATER",
        label: "WATER SUPPORT",
        situation: "Water supply shortage",
        recommendedResource: "NGO Unit 2",
        availability: "AVAILABLE",
        distanceKm: 2.4,
        status: "OPEN",
      },
    ],
  },
];

export const resourceSeed: Resource[] = [
  {
    id: "fire-alpha",
    category: "FIRE",
    name: "Fire Team Alpha",
    status: "AVAILABLE",
    distanceKm: 2.1,
    capacity: 6,
    currentLoad: 0,
  },
  {
    id: "fire-beta",
    category: "FIRE",
    name: "Fire Team Beta",
    status: "AVAILABLE",
    distanceKm: 4.5,
    capacity: 7,
    currentLoad: 1,
  },
  {
    id: "rescue-3",
    category: "RESCUE",
    name: "Rescue Team 3",
    status: "AVAILABLE",
    distanceKm: 2.8,
    capacity: 5,
    currentLoad: 0,
  },
  {
    id: "medical-12",
    category: "MEDICAL",
    name: "Ambulance 12",
    status: "EN_ROUTE",
    distanceKm: 3.1,
    capacity: 2,
    currentLoad: 1,
  },
  {
    id: "ngo-2",
    category: "NGO",
    name: "NGO Unit 2",
    status: "AVAILABLE",
    distanceKm: 2.4,
    capacity: 25,
    currentLoad: 6,
  },
  {
    id: "ngo-4",
    category: "NGO",
    name: "NGO Unit 4",
    status: "AVAILABLE",
    distanceKm: 3.2,
    capacity: 18,
    currentLoad: 4,
  },
];

export const responseTypeLabels: Record<ResponseType, string> = {
  FIRE: "Fire",
  RESCUE: "Rescue",
  MEDICAL: "Medical",
  NGO: "NGO",
  SHELTER: "Shelter",
  FOOD: "Food",
  WATER: "Water",
  VOLUNTEER: "Volunteer",
};
