import type { Incident, Resource, ResponseType } from "@/types/incident";

export const incidentSeed: Incident[] = [
  {
    id: "RX-1042",
    status: "RESPONDING",
    title: "Building fire",
    description:
      "There is a fire in my apartment building. My mother is trapped upstairs and my brother is injured.",
    priority: "CRITICAL",
    createdAt: "2 min ago",
    affectedPeople: 4,
    source: "CITIZEN",
    location: {
      lat: 17.385044,
      lng: 78.486671,
      city: "Hyderabad",
      region: "Telangana",
      label: "Hyderabad, Telangana",
    },
    tags: ["Fire", "Rescue", "Medical"],
    branches: [
      {
        id: "FIRE",
        label: "FIRE RESPONSE",
        situation: "Active building fire",
        recommendedResource: "Fire Team Alpha",
        availability: "AVAILABLE",
        distanceKm: 2.1,
        status: "RESPONDING",
        assignedResourceId: "fire-alpha",
      },
      {
        id: "RESCUE",
        label: "RESCUE REQUIRED",
        situation: "Person trapped upstairs",
        recommendedResource: "Rescue Team 3",
        availability: "AVAILABLE",
        distanceKm: 2.8,
        status: "DISPATCHED",
        assignedResourceId: "rescue-3",
      },
      {
        id: "MEDICAL",
        label: "MEDICAL RESPONSE",
        situation: "Injured person",
        recommendedResource: "Ambulance 12",
        availability: "AVAILABLE",
        distanceKm: 3.1,
        status: "RESPONDING",
        assignedResourceId: "medical-12",
      },
    ],
  },
  {
    id: "RX-1043",
    status: "REVIEWING" as const,
    title: "Flooded street",
    description:
      "A roadside drain overflowed and several vehicles are stranded in the water. People are waiting for help.",
    priority: "HIGH",
    createdAt: "7 min ago",
    affectedPeople: 12,
    source: "CITIZEN",
    location: {
      lat: 17.4566,
      lng: 78.3722,
      city: "Hyderabad",
      region: "Telangana",
      label: "Madhapur, Telangana",
    },
    tags: ["Rescue"],
    branches: [
      {
        id: "RESCUE",
        label: "RESCUE REQUIRED",
        situation: "Vehicles stranded in water",
        recommendedResource: "Rescue Team 2",
        availability: "AVAILABLE",
        distanceKm: 3.4,
        status: "OPEN",
      },
    ],
  },
  {
    id: "RX-1044",
    status: "OPEN",
    title: "Food shortage at temporary shelter",
    description:
      "The shelter is running short on food and water for families displaced by the storm.",
    priority: "MEDIUM",
    createdAt: "15 min ago",
    affectedPeople: 127,
    source: "CITIZEN",
    location: {
      lat: 17.4117,
      lng: 78.4017,
      city: "Hyderabad",
      region: "Telangana",
      label: "Secunderabad, Telangana",
    },
    tags: ["NGO", "Food"],
    branches: [
      {
        id: "FOOD",
        label: "FOOD SUPPORT",
        situation: "Shelter food emergency",
        recommendedResource: "NGO Unit 4",
        availability: "AVAILABLE",
        distanceKm: 3.2,
        status: "OPEN",
      },
      {
        id: "WATER",
        label: "WATER SUPPORT",
        situation: "Water supply shortage",
        recommendedResource: "NGO Unit 2",
        availability: "AVAILABLE",
        distanceKm: 2.4,
        status: "OPEN",
      },
    ],
  },
  {
    id: "RX-1045",
    status: "OPEN",
    title: "Water supply interruption",
    description: "Families at the community hall need drinking water after the supply line was damaged.",
    priority: "MEDIUM",
    createdAt: "22 min ago",
    affectedPeople: 84,
    source: "CITIZEN",
    location: {
      lat: 17.3722,
      lng: 78.4811,
      city: "Hyderabad",
      region: "Telangana",
      label: "Nampally, Telangana",
    },
    tags: ["NGO", "Water"],
    branches: [
      {
        id: "WATER",
        label: "WATER SUPPORT",
        situation: "Drinking water needed at community hall",
        recommendedResource: "NGO Unit 5",
        availability: "AVAILABLE",
        distanceKm: 2.4,
        status: "OPEN",
      },
    ],
  },
  {
    id: "RX-1046",
    status: "OPEN",
    title: "Temporary shelter capacity",
    description: "Displaced residents need temporary shelter and clothing after storm damage to nearby homes.",
    priority: "HIGH",
    createdAt: "29 min ago",
    affectedPeople: 31,
    source: "CITIZEN",
    location: {
      lat: 17.398,
      lng: 78.465,
      city: "Hyderabad",
      region: "Telangana",
      label: "Lakdikapul, Telangana",
    },
    tags: ["NGO", "Shelter", "Clothing"],
    branches: [
      {
        id: "SHELTER",
        label: "SHELTER SUPPORT",
        situation: "Temporary shelter requested",
        recommendedResource: "NGO Unit 3",
        availability: "AVAILABLE",
        distanceKm: 4.1,
        status: "OPEN",
      },
      {
        id: "CLOTHING",
        label: "CLOTHING SUPPORT",
        situation: "Clothing distribution requested",
        recommendedResource: "NGO Unit 1",
        availability: "AVAILABLE",
        distanceKm: 3.8,
        status: "OPEN",
      },
    ],
  },
  {
    id: "RX-1047",
    status: "OPEN",
    title: "Volunteer support needed",
    description: "A local relief point needs volunteers to help organize incoming supplies and assist families.",
    priority: "LOW",
    createdAt: "35 min ago",
    affectedPeople: 12,
    source: "CITIZEN",
    location: {
      lat: 17.405,
      lng: 78.455,
      city: "Hyderabad",
      region: "Telangana",
      label: "Masab Tank, Telangana",
    },
    tags: ["NGO", "Volunteer"],
    branches: [
      {
        id: "VOLUNTEER",
        label: "VOLUNTEER SUPPORT",
        situation: "12 volunteers requested",
        recommendedResource: "NGO Unit 6",
        availability: "AVAILABLE",
        distanceKm: 3.5,
        status: "OPEN",
      },
    ],
  },
];

export const resourceSeed: Resource[] = [
  {
    id: "fire-alpha",
    category: "FIRE",
    name: "Fire Team Alpha",
    status: "EN_ROUTE",
    distanceKm: 2.1,
    capacity: 6,
    currentLoad: 1,
    location: { lat: 17.377, lng: 78.47 },
  },
  {
    id: "fire-beta",
    category: "FIRE",
    name: "Fire Team Beta",
    status: "AVAILABLE",
    distanceKm: 4.5,
    capacity: 7,
    currentLoad: 1,
    location: { lat: 17.403, lng: 78.5 },
  },
  {
    id: "rescue-2",
    category: "RESCUE",
    name: "Rescue Team 2",
    status: "AVAILABLE",
    distanceKm: 3.4,
    capacity: 5,
    currentLoad: 0,
    location: { lat: 17.442, lng: 78.42 },
  },
  {
    id: "rescue-3",
    category: "RESCUE",
    name: "Rescue Team 3",
    status: "EN_ROUTE",
    distanceKm: 2.8,
    capacity: 5,
    currentLoad: 1,
    location: { lat: 17.381, lng: 78.455 },
  },
  {
    id: "rescue-4",
    category: "RESCUE",
    name: "Rescue Team 4",
    status: "AVAILABLE",
    distanceKm: 5.2,
    capacity: 6,
    currentLoad: 1,
    location: { lat: 17.36, lng: 78.52 },
  },
  {
    id: "medical-12",
    category: "MEDICAL",
    name: "Ambulance 12",
    status: "EN_ROUTE",
    distanceKm: 3.1,
    capacity: 2,
    currentLoad: 1,
    location: { lat: 17.39, lng: 78.51 },
  },
  {
    id: "medical-14",
    category: "MEDICAL",
    name: "Ambulance 14",
    status: "AVAILABLE",
    distanceKm: 4.2,
    capacity: 2,
    currentLoad: 0,
    location: { lat: 17.41, lng: 78.47 },
  },
  {
    id: "ngo-2",
    category: "NGO",
    name: "NGO Unit 2",
    status: "AVAILABLE",
    distanceKm: 2.4,
    capacity: 25,
    currentLoad: 6,
    location: { lat: 17.365, lng: 78.46 },
  },
  {
    id: "ngo-4",
    category: "NGO",
    name: "NGO Unit 4",
    status: "AVAILABLE",
    distanceKm: 3.2,
    capacity: 18,
    currentLoad: 4,
    location: { lat: 17.42, lng: 78.49 },
  },
  {
    id: "ngo-1",
    category: "NGO",
    name: "NGO Unit 1",
    status: "AVAILABLE",
    distanceKm: 3.8,
    capacity: 30,
    currentLoad: 9,
    location: { lat: 17.398, lng: 78.45 },
  },
  {
    id: "ngo-3",
    category: "NGO",
    name: "NGO Unit 3",
    status: "AVAILABLE",
    distanceKm: 4.1,
    capacity: 32,
    currentLoad: 11,
    location: { lat: 17.388, lng: 78.505 },
  },
  {
    id: "ngo-5",
    category: "NGO",
    name: "NGO Unit 5",
    status: "AVAILABLE",
    distanceKm: 2.4,
    capacity: 40,
    currentLoad: 5,
    location: { lat: 17.43, lng: 78.46 },
  },
  {
    id: "ngo-6",
    category: "NGO",
    name: "NGO Unit 6",
    status: "AVAILABLE",
    distanceKm: 3.5,
    capacity: 12,
    currentLoad: 0,
    location: { lat: 17.35, lng: 78.48 },
  },
];

export const responseTypeLabels: Record<ResponseType, string> = {
  FIRE: "Fire",
  RESCUE: "Rescue",
  MEDICAL: "Medical",
  NGO: "NGO",
  SHELTER: "Shelter",
  FOOD: "Food",
  WATER: "Water",
  CLOTHING: "Clothing",
  VOLUNTEER: "Volunteer",
};
